version: '3'

services:
  bitbucket-runner:
    image: tactis/bitbucket-runner
    container_name: bitbucket-runner
    volumes:
      - /Volumes/repo:/Volumes/repo:ro # For inventory validation runner
    environment:
      - ACCOUNT_UUID=${ACCOUNT_UUID}
      - REPOSITORY_UUID=${REPOSITORY_UUID}
      - RUNNER_UUID=${RUNNER_UUID}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    command: >
      /atlassian-bitbucket-pipelines-runner/bin/start.sh
      --accountUuid ${ACCOUNT_UUID}
      --repositoryUuid ${REPOSITORY_UUID}
      --runnerUuid ${RUNNER_UUID}
      --OAuthClientId ${OAUTH_CLIENT_ID}
      --OAuthClientSecret ${OAUTH_CLIENT_SECRET}
      --runtime linux-shell
      --workingDirectory /atlassian-bitbucket-pipelines-runner/temp